import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import ReactQueryProvider from '@/components/providers/react-query'
import Navbar from '@/components/navbar'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600', '700'] })

export const metadata: Metadata = { title: 'Create Next App', description: 'Generated by create next app' }

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <ReactQueryProvider>
          <Toaster richColors position="top-right" />
          <Navbar />
          <main>{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  )
}

type Props = Readonly<{ children: React.ReactNode }>
